//     ▄▄ ▄▄ ▄▄  ▄▄▄▄  ▄▄▄▄ ▄▄    ▄▄▄▄▄ ▄▄▄▄
//     ██ ██ ██ ██ ▄▄ ██ ▄▄ ██    ██▄▄  ██▄█▄   Copyright (c) 2026 Julian Storer
//   ▄▄█▀ ▀███▀ ▀███▀ ▀███▀ ██▄▄▄ ██▄▄▄ ██ ██   AGPL-3.0-or-later - see LICENSE

/**
 * base64 conversion tests.
 *
 * bytesToBase64 converts a block at a time, so the sizes either side of that
 * block are the ones that can silently diverge — and a yjs-sync update is
 * opaque binary, so a wrong byte surfaces as a doc that fails to converge
 * rather than as an error. Every case is checked against a per-byte reference
 * encoder, which is what btoa would see given the whole string at once.
 * @module unit-tests/base64-test
 */

import { assert } from '../utilities/test-helpers.js';
import { bytesToBase64, base64ToBytes } from '../../js/utils/base64.js';

/**
 * @typedef {object} TestContext
 * @property {string} fixtureDir - Fixture directory (not used by this test)
 */

/**
 * @typedef {object} TestResult
 * @property {number} passed - Number of passed tests
 * @property {number} failed - Number of failed tests
 * @property {string[]} errors - Error messages for failed tests
 */

/**
 * Encode byte by byte — the straightforward reading of what btoa expects.
 * @param {Uint8Array} bytes - The bytes to encode.
 * @returns {string} The base64 representation.
 */
function referenceEncode(bytes) {
  let binary = '';
  for (let i = 0; i < bytes.length; i++) {
    binary += String.fromCharCode(/** @type {number} */ (bytes[i]));
  }
  return globalThis.btoa(binary);
}

/**
 * Bytes with no repeating structure, so a misplaced block boundary shows up.
 * @param {number} size - How many bytes to generate.
 * @returns {Uint8Array} The generated bytes.
 */
function patternedBytes(size) {
  const bytes = new Uint8Array(size);
  for (let i = 0; i < size; i++) bytes[i] = (i * 2654435761) & 0xff;
  return bytes;
}

/**
 * Run base64 tests.
 * @param {TestContext} _ctx - Test context (unused - this test doesn't need fixtures).
 * @returns {Promise<TestResult>} Test results.
 */
export async function runTests(_ctx) {
  let passed = 0;
  let failed = 0;
  /** @type {string[]} */
  const errors = [];

  // The 0x8000 block, and one byte either side of it and of its second
  // multiple, plus the small sizes that exercise base64's own padding.
  const sizes = [0, 1, 2, 3, 4, 255, 0x7fff, 0x8000, 0x8001, 0xffff, 0x10000, 0x10001];

  try {
    for (const size of sizes) {
      const bytes = patternedBytes(size);
      const encoded = bytesToBase64(bytes);
      assert(
        encoded === referenceEncode(bytes),
        `bytesToBase64 differs from the per-byte reference at ${size} bytes`
      );
      const decoded = base64ToBytes(encoded);
      assert(decoded.length === size, `Round trip of ${size} bytes returned ${decoded.length}`);
      for (let i = 0; i < size; i++) {
        if (decoded[i] !== bytes[i]) {
          throw new Error(`Round trip of ${size} bytes differs at index ${i}`);
        }
      }
    }
    passed++;
  } catch (e) {
    failed++;
    errors.push(`base64 block boundaries: ${e instanceof Error ? e.message : String(e)}`);
  }

  // Uniform content across a block boundary: every byte value is legal in a
  // yjs-sync update, and 0x00 in particular is the one a string-based encoder
  // is most likely to truncate on.
  try {
    for (const fill of [0x00, 0x7f, 0x80, 0xff]) {
      const bytes = new Uint8Array(0x8000 * 2 + 7).fill(fill);
      assert(
        bytesToBase64(bytes) === referenceEncode(bytes),
        `bytesToBase64 differs from the per-byte reference for a buffer of 0x${fill.toString(16)}`
      );
    }
    passed++;
  } catch (e) {
    failed++;
    errors.push(`base64 uniform fills: ${e instanceof Error ? e.message : String(e)}`);
  }

  return { passed, failed, errors };
}
