//     ▄▄ ▄▄ ▄▄  ▄▄▄▄  ▄▄▄▄ ▄▄    ▄▄▄▄▄ ▄▄▄▄
//     ██ ██ ██ ██ ▄▄ ██ ▄▄ ██    ██▄▄  ██▄█▄   Copyright (c) 2026 Julian Storer
//   ▄▄█▀ ▀███▀ ▀███▀ ▀███▀ ██▄▄▄ ██▄▄▄ ██ ██   AGPL-3.0-or-later - see LICENSE

package integration_test

import (
	"encoding/base64"
	"testing"

	ycrdt "github.com/skyterra/y-crdt"
)

// TestYjsCompatibility tests the binary format compatibility between Go y-crdt and JS Yjs.
// This ensures that Yjs updates generated by the Go worker can be correctly decoded
// by the JavaScript frontend.
//
// The test validates:
// 1. Go can encode a Yjs document to binary
// 2. The binary format is valid (non-empty, correct structure)
// 3. Go can decode its own encoded updates (self-apply test)
//
// Manual cross-check with JavaScript:
//  1. Run this test: go test -v ./tests/unit -run TestYjsCompatibility
//  2. Copy the base64 output to web/js-tests/unit-tests/yjs-compat-test.js
//  3. Run: bin/juggler-test --task integration-all
//  4. Verify JavaScript can decode the same update
func TestYjsCompatibility(t *testing.T) {
	// Create a document
	doc := ycrdt.NewDoc("", true, ycrdt.DefaultGCFilter, nil, false)
	items := doc.GetArray("items")

	// Add a simple item as Y.Map (the conversation-item representation)
	doc.Transact(func(trans *ycrdt.Transaction) {
		ymap := ycrdt.NewYMap(map[string]interface{}{
			"type":    "user",
			"content": "Hello, World!",
			"itemId":  "msg_123",
		})
		items.Push(ycrdt.ArrayAny{ymap})
	}, "test-author")

	// Encode the state as a Yjs update
	update := ycrdt.EncodeStateAsUpdate(doc, nil)

	// Log for manual JavaScript cross-check
	t.Logf("Update length: %d bytes", len(update))
	t.Logf("Update (hex): %x", update)
	t.Logf("Update (base64): %s", base64.StdEncoding.EncodeToString(update))
	t.Logf("First byte: 0x%02x", update[0])

	// Validation: Update should not be empty
	if len(update) == 0 {
		t.Fatal("Update should not be empty")
	}

	// Self-apply test: Verify we can apply the update to a new document
	doc2 := ycrdt.NewDoc("", true, ycrdt.DefaultGCFilter, nil, false)
	ycrdt.ApplyUpdate(doc2, update, nil)

	// Verify the item was correctly decoded
	items2 := doc2.GetArray("items")
	if items2.GetLength() != 1 {
		t.Fatalf("Expected 1 item after apply, got %d", items2.GetLength())
	}

	// Verify item contents - should be *YMap
	firstItem := items2.Get(0)
	itemMap, ok := firstItem.(*ycrdt.YMap)
	if !ok {
		t.Fatalf("Expected *YMap, got %T", firstItem)
	}

	if itemMap.Get("type") != "user" {
		t.Errorf("Expected type 'user', got %v", itemMap.Get("type"))
	}
	if itemMap.Get("content") != "Hello, World!" {
		t.Errorf("Expected content 'Hello, World!', got %v", itemMap.Get("content"))
	}
	if itemMap.Get("itemId") != "msg_123" {
		t.Errorf("Expected itemId 'msg_123', got %v", itemMap.Get("itemId"))
	}

	t.Log("Self-apply test passed - Go y-crdt Y.Map binary format is valid")
}

// TestYcrdtNilInObject documents that y-crdt corrupts nil Object values to
// UndefinedType{} during encode/decode, and that omitting the key avoids this.
func TestYcrdtNilInObject(t *testing.T) {
	roundtrip := func(obj ycrdt.Object) ycrdt.Object {
		doc := ycrdt.NewDoc("", true, ycrdt.DefaultGCFilter, nil, false)
		items := doc.GetArray("items")
		doc.Transact(func(trans *ycrdt.Transaction) {
			items.Push(ycrdt.ArrayAny{obj})
		}, "test")
		doc2 := ycrdt.NewDoc("", true, ycrdt.DefaultGCFilter, nil, false)
		ycrdt.ApplyUpdate(doc2, ycrdt.EncodeStateAsUpdate(doc, nil), nil)
		return doc2.GetArray("items").Get(0).(ycrdt.Object)
	}

	// nil value becomes UndefinedType{} after roundtrip (known y-crdt behavior)
	obj1 := ycrdt.NewObject()
	obj1["name"] = "test"
	obj1["warning"] = nil
	decoded1 := roundtrip(obj1)
	if _, ok := decoded1["warning"].(ycrdt.UndefinedType); !ok {
		t.Errorf("expected UndefinedType for nil value, got %T", decoded1["warning"])
	}

	// Omitting the key entirely preserves nil (our fix strategy)
	obj2 := ycrdt.NewObject()
	obj2["name"] = "test"
	decoded2 := roundtrip(obj2)
	if decoded2["warning"] != nil {
		t.Errorf("expected nil for omitted key, got %v (%T)", decoded2["warning"], decoded2["warning"])
	}
}
